import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-primary-fixed": "#241a00",
        "surface-bright": "#2b3d36",
        "tertiary-fixed": "#e2e2e2",
        "surface-container-lowest": "#02110b",
        "on-error": "#690005",
        "primary-fixed-dim": "#e9c255",
        "on-primary-container": "#453400",
        "surface-container-high": "#1c2e27",
        "tertiary-container": "#9e9f9f",
        "on-tertiary-container": "#343637",
        "on-surface-variant": "#d0c5b0",
        "secondary": "#a9cfba",
        "inverse-on-surface": "#22342d",
        "surface-variant": "#273831",
        "surface-container": "#11231c",
        "secondary-fixed-dim": "#a9cfba",
        "on-tertiary-fixed-variant": "#454747",
        "outline-variant": "#4d4636",
        "inverse-primary": "#755b00",
        "surface-container-low": "#0d1f18",
        "on-secondary-fixed": "#002114",
        "primary": "#e9c255",
        "on-tertiary-fixed": "#1a1c1c",
        "error": "#ffb4ab",
        "on-secondary": "#133728",
        "on-tertiary": "#2f3131",
        "secondary-fixed": "#c4ebd6",
        "background": "#051710",
        "tertiary-fixed-dim": "#c6c6c7",
        "surface-tint": "#e9c255",
        "error-container": "#93000a",
        "surface": "#051710",
        "inverse-surface": "#d2e7dd",
        "primary-container": "#bf9b31",
        "on-surface": "#d2e7dd",
        "on-primary-fixed-variant": "#584400",
        "on-secondary-fixed-variant": "#2b4e3e",
        "on-error-container": "#ffdad6",
        "tertiary": "#c6c6c7",
        "on-background": "#d2e7dd",
        "surface-dim": "#051710",
        "surface-container-highest": "#273831",
        "primary-fixed": "#ffdf90",
        "on-primary": "#3d2e00",
        "outline": "#99907d",
        "on-secondary-container": "#98bea9",
        "secondary-container": "#2b4e3e"
      },
      fontFamily: {
        "headline": ["Noto Serif", "serif"],
        "body": ["Manrope", "sans-serif"],
        "label": ["Manrope", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "0.125rem", 
        "lg": "0.25rem", 
        "xl": "0.5rem", 
        "full": "0.75rem"
      },
      spacing: {
        '0': '0rem',
        '0.5': '0.125rem',
        '1': '0.25rem',
        '1.5': '0.375rem',
        '2': '0.5rem',
        '3': '0.75rem',
        '4': '1rem',
        '5': '1.25rem',
        '6': '1.5rem',
        '8': '2rem',
        '10': '2.5rem',
        '12': '3rem',
        '16': '4rem',
        '20': '5rem',
        '24': '6rem',
        '32': '8rem',
      }
    },
  },
  plugins: [],
};
export default config;
